seq : gameOfCivilization.h gameOfCivilizationSequential.h gameOfCivilizationSequential.cpp main.cpp
	g++ -std=c++11 -o seqGame gameOfCivilization.h gameOfCivilizationSequential.h gameOfCivilizationSequential.cpp main.cpp
